import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { createReadStream, existsSync, statSync } from 'node:fs';
import { extname, join, normalize } from 'node:path';
const DIST='/tmp/anth-dist/ch41', BASE='/anthropocene';
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' };
const srv = createServer((req, res) => { let p = decodeURIComponent(req.url.split('?')[0]); if (p.startsWith(BASE)) p = p.slice(BASE.length) || '/'; let f = normalize(join(DIST, p)); if (existsSync(f) && statSync(f).isDirectory()) f = join(f, 'index.html'); if (!existsSync(f)) { res.writeHead(404).end(); return; } res.writeHead(200, { 'content-type': MIME[extname(f)] || 'application/octet-stream' }); createReadStream(f).pipe(res); });
await new Promise((r) => srv.listen(0, r));
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader', '--enable-webgl', '--ignore-gpu-blocklist'] });
const pg = await b.newPage({ viewport: { width: 1300, height: 1000 } });
const msgs=[]; pg.on('console', (m) => msgs.push(m.type()+': '+m.text())); pg.on('pageerror', e=>msgs.push('pageerror '+e.message));
await pg.goto(`http://localhost:${srv.address().port}${BASE}/learn/university-physics/atoms/a-cloud-with-dark-shells/?all`);
const w = pg.locator('[data-widget-id="up-ch41-shell-bet"]'); await w.scrollIntoViewIfNeeded(); await pg.waitForTimeout(800);
await w.getByText('One about 50 pm').click(); await w.getByRole('button', { name: /commit/i }).click(); await pg.waitForTimeout(2500);
const info = await pg.evaluate(() => [...document.querySelectorAll('canvas')].map(c => ({ w: c.width, h: c.height, cw: c.clientWidth, ch: c.clientHeight, top: Math.round(c.getBoundingClientRect().top) })));
console.log(JSON.stringify(info)); console.log(msgs.join('\n'));
await b.close(); srv.close();
