import { splitQV } from './ode.ts';
import type { State } from './types.ts';

/* ─────────────────────────────────────────────────────────────────────────
   Discrete Lagrangian mechanics (Marsden & West 2001, §§1.3 and 2.6.2).

   The continuous action is ∫ L(q, q̇) dt. A variational integrator replaces
   that integral with a sum of discrete Lagrangians L_d(q_k, q_{k+1}, h), then
   demands that the discrete action be stationary. The resulting discrete
   Euler–Lagrange equation IS the update.

   For a mechanical Lagrangian L = ½ m |q̇|² − V(q), the symmetric
   (trapezoidal) choice

     L_d(q₀, q₁, h) = (h/2) L(q₀, (q₁−q₀)/h) + (h/2) L(q₁, (q₁−q₀)/h)

   uses the midpoint velocity (q₁−q₀)/h and averages the potential at the
   two endpoints. Stationarity of this L_d is velocity Verlet — derived, not
   imposed. The true midpoint quadrature of L (V evaluated at (q₀+q₁)/2)
   gives implicit midpoint instead; we do not use that one here.

   These functions are written to be read. The widget never reimplements
   Verlet: it steps with `velocityVerlet` from ode.ts. Tests here prove that
   the discrete-Lagrangian map and that stepper are the same map.
   ───────────────────────────────────────────────────────────────────────── */

export type Potential = (q: State) => number;
export type Force = (q: State) => State; // ∇V, so acceleration is −∇V / m

/** Symmetric discrete Lagrangian of a unit-or-given mass mechanical system. */
export function discreteLagrangian(
  q0: State,
  q1: State,
  h: number,
  V: Potential,
  mass = 1,
): number {
  let v2 = 0;
  for (let i = 0; i < q0.length; i++) {
    const vi = (q1[i] - q0[i]) / h;
    v2 += vi * vi;
  }
  return h * (0.5 * mass * v2 - 0.5 * (V(q0) + V(q1)));
}

/** Fibre derivatives of L_d.
 *
 *  L_d = (m / (2h)) |q₁ − q₀|² − (h/2) (V(q₀) + V(q₁))
 *
 *    D1 L_d = ∂L_d/∂q₀ = − (m/h)(q₁ − q₀) − (h/2) ∇V(q₀)
 *    D2 L_d = ∂L_d/∂q₁ =   (m/h)(q₁ − q₀) − (h/2) ∇V(q₁)
 */
export function fibreDerivatives(
  q0: State,
  q1: State,
  h: number,
  gradV: Force,
  mass = 1,
): { D1: State; D2: State } {
  const g0 = gradV(q0);
  const g1 = gradV(q1);
  const D1 = q0.map((qi, i) => -(mass / h) * (q1[i] - qi) - 0.5 * h * g0[i]);
  const D2 = q0.map((_, i) => (mass / h) * (q1[i] - q0[i]) - 0.5 * h * g1[i]);
  return { D1, D2 };
}

/** Discrete Legendre transforms: p₀ = −D1 L_d, p₁ = D2 L_d. */
export function discreteMomenta(
  q0: State,
  q1: State,
  h: number,
  gradV: Force,
  mass = 1,
): { p0: State; p1: State } {
  const { D1, D2 } = fibreDerivatives(q0, q1, h, gradV, mass);
  return { p0: D1.map((d) => -d), p1: D2 };
}

/** Discrete Euler–Lagrange residual at an interior point q_k:
 *  D2 L_d(q_{k−1}, q_k) + D1 L_d(q_k, q_{k+1}).
 *  Stationary discrete paths make this the zero vector. */
export function delResidual(
  qPrev: State,
  q: State,
  qNext: State,
  h: number,
  gradV: Force,
  mass = 1,
): State {
  const left = fibreDerivatives(qPrev, q, h, gradV, mass).D2;
  const right = fibreDerivatives(q, qNext, h, gradV, mass).D1;
  return left.map((li, i) => li + right[i]);
}

/** One step of the discrete Hamiltonian map generated by L_d.
 *
 *  Solve p = −D1 L_d(q, q₊) for q₊, then p₊ = D2 L_d(q, q₊). For this
 *  L_d that is explicit, and it is velocity Verlet:
 *
 *    q₊ = q + (h/m) p − (h² / (2m)) ∇V(q)
 *    p₊ = p − (h/2) (∇V(q) + ∇V(q₊))
 */
export function discreteLagrangianStep(
  q: State,
  p: State,
  h: number,
  gradV: Force,
  mass = 1,
): { q: State; p: State } {
  const g = gradV(q);
  const qNext = q.map((qi, i) => qi + (h / mass) * p[i] - ((h * h) / (2 * mass)) * g[i]);
  const gNext = gradV(qNext);
  const pNext = p.map((pi, i) => pi - 0.5 * h * (g[i] + gNext[i]));
  return { q: qNext, p: pNext };
}

/** Pack the discrete-Lagrangian map as a first-order stepper on [q, v]
 *  state (unit mass ⇒ p = v), so tests can compare it to `velocityVerlet`. */
export function discreteLagrangianStepper(gradV: Force, mass = 1) {
  return (_t: number, y: State, h: number): State => {
    const { q, v } = splitQV(y);
    const p = mass === 1 ? v : v.map((vi) => mass * vi);
    const next = discreteLagrangianStep(q, p, h, gradV, mass);
    const vNext = mass === 1 ? next.p : next.p.map((pi) => pi / mass);
    return [...next.q, ...vNext];
  };
}

/** 2-D scalar angular momentum q_x p_y − q_y p_x. */
export function angularMomentum2d(q: State, p: State): number {
  return q[0] * p[1] - q[1] * p[0];
}

/** Reverse momenta: R(q, v) = (q, −v). */
export function reverseMomenta(y: State): State {
  const { q, v } = splitQV(y);
  return [...q, ...v.map((vi) => -vi)];
}
